# Tensors
Tensors are a specialized data structure, similar to arrays and matrices. Tensors can be used to encode inputs and outputs of a model, as well as the model's parameters.
Tensors are similar to NumPy's ndarrays, except that tensors can run on GPUs or other hardware accelerators. Tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data.

In [5]:
import torch
import numpy as np

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")
# a change in the tensor reflects in the NumPy array
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")
# NumPy array can generate a tensor
m = np.ones(5)
u = torch.from_numpy(m)
print(f"m: {m}")
print(f"u: {u}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
m: [1. 1. 1. 1. 1.]
u: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


## Initializing a Tensor

In [5]:
import torch
import numpy as np

# directly from data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
# from a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
# from another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor; \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")
# with random or constant values
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Ones Tensor; 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.9909, 0.8039],
        [0.2714, 0.6522]]) 

Random Tensor: 
 tensor([[0.8646, 0.9171, 0.5131],
        [0.6682, 0.2453, 0.0314]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor

In [6]:
import torch
import numpy as np

tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors
The [torch package](https://pytorch.org/docs/stable/torch.html) contains over 100 operations. By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using 
`.to` 
method (after checking for GPU availability). 

In [2]:
import torch

if torch.cuda.is_available():
    tensor = tensor.to("cuda")

# Sources
* https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html